site_name: SaaS Big Data Demo
repo_url: https://github.com/jbcodeforce/big-data-tenant-analytics.git
nav:
  - Introduction: index.md
  - Business Dashboard: dashboard.md
  - Architecture & Design: design.md
  - EKS: eks.md
  - ML model: model.md
  - API Gateway - Lambda: api-lambda.md
  - RT Analytics: rt-analytics.md
  - Tenant Manager: java-apps.md
  - Infrastructure as code: cdk.md
  - AWS studies: https://jbcodeforce.github.io/aws-studies/
  
theme: 
  name: material
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      # - navigation.tabs
      - navigation.instant
      - navigation.tracking
      # - navigation.sections
      # - navigation.expand
      - navigation.tabs.sticky
      # - navigation.top

  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true